version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - ENV_DIR=.
    command: ["task", "start"]
